name    'stesie-gluon'
version '0.1.0'
source 'https://github.com/ffansbach/gluon-puppet'
author 'stesie'
license 'Apache License, Version 2.0'
summary 'puppet module to ease setup of gluon gateway server'
description 'A puppet module to set up everything needed for a Freifunk Mesh Gateway, using Gluon firmware.'
project_page 'https://github.com/ffansbach/'

dependency 'puppetlabs/apache', '>= 1.1.1'
dependency 'puppetlabs/apt', '>= 1.6.0'
dependency 'puppetlabs/concat', '>= 1.1.1'
dependency 'puppetlabs/firewall', '>= 1.1.3'
dependency 'camptocamp/kmod', '>= 0.1.3'
dependency 'puppetlabs/mysql', '>= 2.3.1'
dependency 'example42/network', '>= 3.1.14'
dependency 'puppetlabs/stdlib', '>= 4.3.2'
dependency 'thias/sysctl', '>= 1.0.0'

