class gluon::radvd {
    # install radvd and prepare config collection
    # snippets for /etc/radvd.conf provided by gluon::mesh_vpn
    package { 'radvd':
	ensure      => present,
    }

    concat { '/etc/radvd.conf':
	ensure      => present,
	notify      => Service['radvd'],
    }

    concat::fragment { "radvd-base":
	target      => "/etc/radvd.conf",
	content     => "# auto-generated by puppet\n",
    }

    service { 'radvd':
	ensure      => running,
	require     => Package['radvd'],
    }
}
